In [14]:
import pandas as pd
import numpy as np

students = pd.read_csv("Students.csv")
mentors = pd.read_csv("Mentors.csv")

print students
print mentors

student_choice1_weight = 0 # student's choice-1 = mentor's choice
student_choice2_weight = 1 # student's choice-2 = mentor's choice
student_nonchoice_weight = 2 # mentors's choice is different from student's choice-1,2
#mentor_choice_weight = 0
#mentor_nonchoice_weight = 1

N = students.shape[0]
print N

Cost = np.zeros((N,N))

print Cost

for ii in range(N):
    for jj in range(N):
        seniority = students.iloc[ii]["Seniority"]
        student_choice1 = students.iloc[ii]["Choice-1"]
        student_choice2 = students.iloc[ii]["Choice-2"]
        mentor_choice = mentors.iloc[jj]["Choice"]
        if student_choice1 == mentor_choice: 
            weight = student_choice1_weight
        elif student_choice2 == mentor_choice: 
            weight = student_choice2_weight
        else: 
            weight = student_nonchoice_weight
            
        Cost[ii][jj] = float(seniority*weight)

print Cost

from scipy.optimize import linear_sum_assignment
row_ind, col_ind = linear_sum_assignment(Cost)

print row_ind
print col_ind

for ii in range(N):
    print students.iloc[ii]["Student Name"], mentors.iloc[col_ind[ii]]["Mentor Name"]

  Student Name  Seniority Choice-1 Choice-2
0          ABC          1        X        Y
1          BCD          4        P        Z
2          CDE          3        Z        X
3          DEF          3        Y        W
4          EFG          2        W        P
5          FGH          1        X        P
  Mentor Name Choice
0         abc      P
1         bcd      X
2         cde      Y
3         def      Z
4         efg      Z
5         fgh      W
6
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[2. 0. 1. 2. 2. 2.]
 [0. 8. 8. 4. 4. 8.]
 [6. 3. 6. 0. 0. 6.]
 [6. 6. 0. 6. 6. 3.]
 [2. 4. 4. 4. 4. 0.]
 [1. 0. 2. 2. 2. 2.]]
[0 1 2 3 4 5]
[3 0 4 2 5 1]
ABC def
BCD abc
CDE efg
DEF cde
EFG fgh
FGH bcd
